import "reflect-metadata";
import { ClassModule, DevicesInformation } from "../../types";
export declare class BRP069C4x implements ClassModule {
    private _device;
    private _isHolidayModeActive?;
    private _isInErrorState?;
    private _isInWarningState?;
    private _isInModeConflict?;
    private _isInCautionState?;
    private _isCoolHeatMaster?;
    private _operationMode?;
    private _onOffMode?;
    private _econoMode?;
    private _powerfulMode?;
    private _streamerMode?;
    private _roomTemperature?;
    private _outdoorTemperature?;
    private _outdoorSilentMode?;
    private _temperatureControl?;
    private _fanCurrentMode?;
    private _fanFixed?;
    private _fanHorizontal?;
    private _fanVertical?;
    private _heatingConsumptionD?;
    private _heatingConsumptionW?;
    private _heatingConsumptionM?;
    private _coolingConsumptionD?;
    private _coolingConsumptionW?;
    private _coolingConsumptionM?;
    set outdoorSilentMode(value: boolean);
    set streamerMode(value: boolean);
    set powerfulMode(value: boolean);
    set econoMode(value: boolean);
    set onOffMode(value: boolean);
    set operationMode(value: string);
    set isCoolHeatMaster(value: boolean);
    set isHolidayModeActive(value: boolean);
    set isInErrorState(value: boolean);
    set isInWarningState(value: boolean);
    set isInCautionState(value: boolean);
    set roomTemperature(value: number);
    set outdoorTemperature(value: number);
    set temperatureControl(value: number);
    set fanVertical(value: string);
    set fanHorizontal(value: string);
    set fanFixed(value: string);
    set fanCurrentMode(value: string);
    set device(value: DevicesInformation);
    constructor(device: any);
}
