import { ClassModule, DevicesInformation } from "../../types";
export declare class BRP069A61 implements ClassModule {
    private _device;
    private _isHolidayModeActive1?;
    private _isInErrorState1?;
    private _isInWarningState1?;
    private _isInInstallerState1?;
    private _isInEmergencyState1?;
    private _onOffMode1?;
    private _setpointMode1?;
    private _controlMode1?;
    private _outdoorTemperature1?;
    private _isHolidayModeActive2?;
    private _isInErrorState2?;
    private _isInWarningState2?;
    private _isInInstallerState2?;
    private _isInEmergencyState2?;
    private _onOffMode2?;
    private _operationMode2?;
    private _powerfulMode?;
    private _heatupMode2?;
    private _tankTemperature2?;
    private _temperatureControl?;
    private _setpointMode2?;
    set isHolidayModeActive1(value: boolean);
    set isInErrorState1(value: boolean);
    set isInWarningState1(value: boolean);
    set isInInstallerState1(value: boolean);
    set isInEmergencyState1(value: boolean);
    set onOffMode1(value: boolean);
    set setpointMode1(value: boolean);
    set controlMode1(value: boolean);
    set outdoorTemperature1(value: number);
    set isHolidayModeActive2(value: boolean);
    set isInErrorState2(value: boolean);
    set isInWarningState2(value: boolean);
    set isInInstallerState2(value: boolean);
    set isInEmergencyState2(value: boolean);
    set onOffMode2(value: boolean);
    set operationMode2(value: string);
    set powerfulMode(value: boolean);
    set heatupMode2(value: string);
    set tankTemperature2(value: number);
    set temperatureControl(value: number);
    set setpointMode2(value: boolean);
    set device(value: DevicesInformation);
    constructor(device: any);
}
