import "reflect-metadata";
import { ClassModule, DevicesInformation } from "../../types";
export declare class SystemBridge implements ClassModule {
    private _device;
    get device(): DevicesInformation;
    set device(value: DevicesInformation);
    private _rateLimitMinute?;
    private _rateRemainingMinute?;
    private _rateLimitDay?;
    private _rateRemainingDay?;
    private _modulesCount?;
    private _modulesList?;
    private _unsupportedModulesCount?;
    private _unsupportedModulesList?;
    private _refreshAllDevices?;
    private _authorizationUrl?;
    private _authorizationRequest?;
    private _authorizationTimeout?;
    private _apiBudgetStatus?;
    private _nextPollingAt?;
    private _skippedRefreshCount?;
    private _authMode?;
    private _webSocketConnected?;
    private _dailyQuotaLimit?;
    constructor();
    get rateLimitMinute(): number | undefined;
    set rateLimitMinute(value: number | undefined);
    get rateRemainingMinute(): number | undefined;
    set rateRemainingMinute(value: number | undefined);
    get rateLimitDay(): number | undefined;
    set rateLimitDay(value: number | undefined);
    get rateRemainingDay(): number | undefined;
    set rateRemainingDay(value: number | undefined);
    get modulesCount(): number | undefined;
    set modulesCount(value: number | undefined);
    get modulesList(): string | undefined;
    set modulesList(value: string | undefined);
    get unsupportedModulesCount(): number | undefined;
    set unsupportedModulesCount(value: number | undefined);
    get unsupportedModulesList(): string | undefined;
    set unsupportedModulesList(value: string | undefined);
    get refreshAllDevices(): boolean | undefined;
    set refreshAllDevices(value: boolean | undefined);
    get authorizationUrl(): string | undefined;
    set authorizationUrl(value: string | undefined);
    get authorizationRequest(): boolean | undefined;
    set authorizationRequest(value: boolean | undefined);
    get authorizationTimeout(): boolean | undefined;
    set authorizationTimeout(value: boolean | undefined);
    get apiBudgetStatus(): string | undefined;
    set apiBudgetStatus(value: string | undefined);
    get nextPollingAt(): number | undefined;
    set nextPollingAt(value: number | undefined);
    get skippedRefreshCount(): number | undefined;
    set skippedRefreshCount(value: number | undefined);
    get authMode(): string | undefined;
    set authMode(value: string | undefined);
    get webSocketConnected(): boolean | undefined;
    set webSocketConnected(value: boolean | undefined);
    get dailyQuotaLimit(): number | undefined;
    set dailyQuotaLimit(value: number | undefined);
}
