system:
  logLevel: 'info' # Indicates the level of log that the system must use
  jeedom: false # Activate the integration for the Jeedom home automation system
daikin:
  clientID: null # Client ID allowing connection to the Daikin Onecta Cloud
  clientSecret: null # Client Secret allowing connection to the Daikin Onecta cloud
  clientURL: ""
  clientPort: 8765
mqtt:
  host: "127.0.0.1" # MQTT broker IP address
  port: 1883 # MQTT broker port
  auth: false # Defines whether the MQTT broker requires MQTT authentication
  username: null # Identifier allowing authentication with the mqtt broker
  password: null # Password allowing authentication with the mqtt broker
  connectTimeout: 4000 # Time in ms before the communication is considered in timeout
  reconnectPeriod: 1000 # Time before connecting to MQTT broker in case of communication loss
  topic: "daikinToMQTT" # Topic MQTT where the software information will be published
