name: Build
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: 18
              cache: yarn
          - run: yarn
          - run: yarn build
          - run: yarn package
          - uses: int128/release-typescript-action@v1
